### ISSUE TITLE
How to do lazy routing?

### ISSUE THREAD

**Issue by zifahm** [vjee/vite-plugin-remix-routes#7]
Is there a way to add lazy to all generated routes?

**Comment by vjee** [comment]
If you're not using a a router that supports data APIs (See https://reactrouter.com/en/main/routers/picking-a-router#using-v64-data-apis), then you can do the following:
```js
remixRoutes({
  // the `importMode` option only works with `dataRouterCompatible` set to `false`
  dataRouterCompatible: false,

  // make all routes async unconditionally
  importMode: (route) => 'async',
});
```
